# Packs the frames art/frames.mjs captured into one module per theme for the terminal.
#   python3 art/pack.py      (after node art/frames.mjs)   -> themes/frames/<name>.js and themes/frames/index.js
# Each frame is quantized to a small palette, identical frames are stored once, and each state lists its
# intro (played once) and loop (repeated) as indexes into the theme's frames.
import base64, hashlib, io, json, os, glob
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'art', '.frames')
OUT = os.path.join(ROOT, 'themes', 'frames')
# Terminal columns per CSS pixel of art width: a 20px-tall drawing in one row whose cells are about 1:2.6
# (Ghostty and kitty on a Retina screen); a squarer cell only widens the picture slightly
COLUMNS_PER_PX = 0.129


def png(path):
    im = Image.open(path).convert('RGBA')
    small = im.quantize(colors=32, method=Image.Quantize.FASTOCTREE)
    buf = io.BytesIO()
    small.save(buf, 'PNG', optimize=True)
    return buf.getvalue()


def main():
    manifest = json.load(open(os.path.join(SRC, 'manifest.json')))
    os.makedirs(OUT, exist_ok=True)
    names, total = [], 0
    for name, theme in manifest['themes'].items():
        frames, index, states = [], {}, {}
        for state, info in theme['states'].items():
            ids = []
            for path in sorted(glob.glob(os.path.join(SRC, name, f'{state}-*.png'))):
                data = png(path)
                key = hashlib.sha1(data).hexdigest()
                if key not in index:
                    index[key] = len(frames)
                    frames.append(base64.b64encode(data).decode())
                ids.append(index[key])
            states[state] = {'intro': ids[:info['intro']], 'loop': ids[info['intro']:] or ids[-1:]}
        columns = max(2, round(theme['cssWidth'] * COLUMNS_PER_PX))
        body = json.dumps({'name': name, 'columns': columns, 'fps': manifest['fps'], 'states': states}, separators=(',', ':'))
        lines = [
            f'// {name}: terminal frames, generated by art/frames.mjs and art/pack.py from themes/. Do not edit.',
            f'export default {{ ...{body}, frames: [',
            *[f"  '{b}'," for b in frames],
            ']}',
            '',
        ]
        text = '\n'.join(lines)
        open(os.path.join(OUT, f'{name}.js'), 'w').write(text)
        total += len(text)
        names.append(name)
        print(f'{name}: {len(frames)} unique frames, {columns} columns, {len(text) // 1024} KB')
    imports = '\n'.join(f"import {n} from './{n}.js'" for n in names)
    open(os.path.join(OUT, 'index.js'), 'w').write(
        '// Terminal frames for every theme, by name. Generated by art/pack.py. Do not edit.\n'
        f'{imports}\n\nexport const FRAMES = {{ {", ".join(names)} }}\n')
    print(f'total {total // 1024} KB')


if __name__ == '__main__':
    main()
