// Terminal frames for every theme, by name. Generated by art/pack.py. Do not edit.
import rewind from './rewind.js'
import channel3 from './channel3.js'
import cassette from './cassette.js'
import platform from './platform.js'
import arrivals from './arrivals.js'
import sandglass from './sandglass.js'
import floppy from './floppy.js'
import dotmatrix from './dotmatrix.js'
import pong from './pong.js'
import filmstrip from './filmstrip.js'

export const FRAMES = { rewind, channel3, cassette, platform, arrivals, sandglass, floppy, dotmatrix, pong, filmstrip }
